name:                wikipediastats
version:             0.1.0.0
github:              "doersino/wikipediastats"
license:             BSD3
author:              "Noah Doersing"
maintainer:          "git@noahdoersing.com"
copyright:           "2020 Noah Doersing"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/doersino/wikipediastats#readme>

dependencies:
- base >= 4.7 && < 5
- text
- xml-types
- xml-conduit
- http-conduit
- html-conduit
- twitter-conduit
- json
- directory
- containers

library:
  source-dirs: src

executables:
  wikipediastats-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wikipediastats

tests:
  wikipediastats-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wikipediastats
